/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
    [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface AuthUsers {
    created_at: Generated<Timestamp>
    email: string
    email_verified: Generated<boolean>
    id: Generated<number>
    is_banned: Generated<boolean>
    password: string
    role_id: number
    updated_at: Generated<Timestamp>
}

export interface Cache {
    created_at: Generated<Timestamp>
    expires_at: Timestamp | null
    key: string
    value: Json
}

export interface Permissions {
    created_at: Generated<Timestamp>
    description: Generated<string>
    id: Generated<number>
    label: string
    module: string
    slug: string
}

export interface RolePermissions {
    permission_id: number
    role_id: number
}

export interface Roles {
    created_at: Generated<Timestamp>
    description: string | null
    id: Generated<number>
    is_system: Generated<boolean>
    label: string
    slug: string
    updated_at: Generated<Timestamp>
}

export interface DB {
    auth_users: AuthUsers
    cache: Cache
    permissions: Permissions
    role_permissions: RolePermissions
    roles: Roles
}
